# Generated by Django 5.0.2 on 2024-10-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0002_alter_frase_options_alter_alumnot_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table='Alumnos',
        ),
    ]
